apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-pod
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: busybox-writer
      image: busybox
      command: [ "sh", "-c", "while true; do date > /data/index.html; sleep 5; done" ]
      volumeMounts:
        - name: shared-data
          mountPath: /data

    - name: nginx-server
      image: nginx:1.21
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
