apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    name: mysql
  # headless service
  # Instead of a single virtual IP, the Service directly returns the DNS records of the individual Pods.
  clusterIP: None   
  selector:
    app: mysql
